<?php

require_once 'header.php';

function secretkey($total_lenght) {

    $output_code = NULL;
    $total_lenght - 1;
    $part = 1;
    $code = array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','0','1','2','3','4','5','6','7','8','9');
        while ($part <= $total_lenght) {
            $output_code .= $code[rand(0,61)];
            $part ++;
        }
    return $output_code;
}

 ?>

    <div class="container">
		<ul class="wizard">
			<li class="text-muted"><span class="badge">1 <i class="fa fa-check fa-fw"></i></span> <span class="hidden-xs">Welcome</span></li>
			<li class="active"><span class="badge">2</span> <span class="hidden-xs">Configuration</span></li>
			<li><span class="badge">3</span> <span class="hidden-xs">Installation</span></li>
			<li><span class="badge">4</span> <span class="hidden-xs">Finished</span></li>
		</ul>

		<div class="content">
			<h1>Configuration</h1><hr/>
			<form role="form" name="form" class="row center-text">
				<div class="form-section col-sm-6">
					<h2>Database</h2>
					<div class="form-group">
						 <label>Hostname</label><input type="text" class="form-control" name="hostname" placeholder="localhost" required autofocus="true" />
					</div>
					<div class="form-group">
						 <label>Username</label><input type="text" class="form-control" name="username" placeholder="root" required />
					</div>
					<div class="form-group">
						 <label>Password</label><input type="password" class="form-control" name="password" placeholder="" />
					</div>
					<div class="form-group">
						 <label>Database</label><input type="text" class="form-control" name="database" placeholder="ban-management" required />
					</div>
					<div class="form-group">
						 <label>Table Prefix</label><input type="text" class="form-control" name="prefix" placeholder="bm_" />
						 <span class="help-block">This table prefix will be used for all tables generated by this site.</span>
					</div>
				</div>

				<div class="form-section col-sm-6">
					<h2>System settings</h2>
					<div class="form-group">
						 <label>Site URL</label><input type="text" class="form-control" name="location" placeholder="http://www.awesome-server.com" />
					</div>
					<div class="form-group">
						 <label>Locale</label>
						 <select name="locale" size="1" class="form-control">
						  <option>en</option>
						  <option>de</option>
						</select>
					</div>
					<div class="form-group">
						 <label>Security Key</label><input type="text" class="form-control" name="password" maxlength="32" value="<? echo secretkey(32) ?>" required />
             <span class="help-block">This can't be longer then 32 chars</span>
					</div>
					<div class="form-group">
						<label><i class="fa fa-info-circle"></i> Heads up!</label>
						 <p>Once the installation is finished, please go on creating a master account for the admin panel.</p>
					</div>
				</div>
			</form>
		</div>

		<div class="buttons">
			<a href="step3.php" class="btn btn-primary">Continue <i class="fa fa-chevron-right"></i></a>
		</div>

		<div class="footer">
			<hr>
			&copy; 2014 by the <a href="https://github.com/ftbastler/Ban-Management-Web/graphs/contributors">Ban-Management WebApp crew</a>.
		</div>
    </div>

<?php require_once "footer.php"; ?>
